# ----------------------- #
#      Main Configs       #
# ----------------------- #

url: https://turtletrafo.de

title: Turtle Transformation
email: info@turtletrafo.de
author: Miriam & Markus Schmidberger
description: 'Wir teilen mit Dir unseren Weg und begleiten Dich auf Deiner Transformation als Individuum, als Familie oder als Firma.'
copyright: 'Copyright &copy; 2020 Miriam & Markus Schmidberger. All Rights Reserved.'
credits: ''
keep_files: [CNAME]

# Google tracking, if both are filled, tag manager will prevail. Set up GA through GTM in that case
google_analytics_tracking_id: G-21YC88FWVZ

# ----------------------- #
#    Jekyll & Plugins     #
# ----------------------- #

# Build settings
markdown: kramdown
#remote_theme: swcool/landing-page-theme
permalink: pretty # layout of URL for blog posts
plugins:
  - jekyll-minifier
  - jekyll-sitemap
  - jekyll-github-metadata #Jekyll plugin to propagate the site.github namespace and set default values for use with GitHub Pages.
  - jekyll-multiple-languages-plugin

github: [metadata]

# languages
languages: ["de", "en"]
exclude_from_localizations: ["assets", "css", "fonts", "img", "js", "CNAME", favicon.ico, docs, apple-touch-icon.png, robots.txt]
exclude:
  - README.md
  - Gemfile.lock
  - Gemfile
defaultLang: de
languageNames:
  de: Deutsch
  en: English

# ----------------------- #
#   3rd Party Settings    #
# ----------------------- #

social:
  - title: envelope
    title2: E-Mail
    url: mailto:info@turtletrafo.de
  - title: linkedin
    url: https://de.linkedin.com/company/turtletrafo
  - title: facebook
    url: https://www.facebook.com/turtletrafo
  - title: instagram
    url: https://www.instagram.com/turtletrafo
  - title: youtube
    url: https://www.youtube.com/@turtletrafo
